In [1]:
import numpy as np

In [9]:
y=np.ones((50,60),dtype=int)
x=y

In [10]:
x

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [11]:
y

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [19]:
twoD_array=np.arange(12100).reshape(110,110)
twoD_array

array([[    0,     1,     2, ...,   107,   108,   109],
       [  110,   111,   112, ...,   217,   218,   219],
       [  220,   221,   222, ...,   327,   328,   329],
       ...,
       [11770, 11771, 11772, ..., 11877, 11878, 11879],
       [11880, 11881, 11882, ..., 11987, 11988, 11989],
       [11990, 11991, 11992, ..., 12097, 12098, 12099]])

In [22]:
twoD_array[-20:,2:6]

array([[ 9902,  9903,  9904,  9905],
       [10012, 10013, 10014, 10015],
       [10122, 10123, 10124, 10125],
       [10232, 10233, 10234, 10235],
       [10342, 10343, 10344, 10345],
       [10452, 10453, 10454, 10455],
       [10562, 10563, 10564, 10565],
       [10672, 10673, 10674, 10675],
       [10782, 10783, 10784, 10785],
       [10892, 10893, 10894, 10895],
       [11002, 11003, 11004, 11005],
       [11112, 11113, 11114, 11115],
       [11222, 11223, 11224, 11225],
       [11332, 11333, 11334, 11335],
       [11442, 11443, 11444, 11445],
       [11552, 11553, 11554, 11555],
       [11662, 11663, 11664, 11665],
       [11772, 11773, 11774, 11775],
       [11882, 11883, 11884, 11885],
       [11992, 11993, 11994, 11995]])

In [25]:
oneD_array=twoD_array.ravel()

In [26]:
oneD_array

array([    0,     1,     2, ..., 12097, 12098, 12099])

In [27]:
x=np.arange(36).reshape(6,6)

In [33]:
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [34]:
x.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [35]:
import numpy as np
x=np.array([[1,2] , [3,4]])
y=np.array([ [5,6],[7,8]])
z=(x*y)
z

array([[ 5, 12],
       [21, 32]])

In [37]:
import numpy as np
x=np.array([4,6,2,8])
np.median(x)

5.0