In [1]:
import numpy as np

In [2]:
x=np.arange(10)**3

In [7]:
for i in x:
    print(i)

0
1
8
27
64
125
216
343
512
729


In [8]:
emp=np.array([['TCS','Capgemini','Reliance','IBM','Microsoft','Seimens','NTT Data'],
                   [50000,90000,89000,789000,450000,670000,76000],
                   [0.7,0.9,0.45,1.00,87.5,78.5,89.7]])

In [14]:
emp

array([['TCS', 'Capgemini', 'Reliance', 'IBM', 'Microsoft', 'Seimens',
        'NTT Data'],
       ['50000', '90000', '89000', '789000', '450000', '670000', '76000'],
       ['0.7', '0.9', '0.45', '1.0', '87.5', '78.5', '89.7']],
      dtype='<U32')

In [12]:
i=0
for item in emp:
    print('Row',i,':',item)
    i+=1

Row 0 : ['TCS' 'Capgemini' 'Reliance' 'IBM' 'Microsoft' 'Seimens' 'NTT Data']
Row 1 : ['50000' '90000' '89000' '789000' '450000' '670000' '76000']
Row 2 : ['0.7' '0.9' '0.45' '1.0' '87.5' '78.5' '89.7']


In [17]:
emp.flatten()

array(['TCS', 'Capgemini', 'Reliance', 'IBM', 'Microsoft', 'Seimens',
       'NTT Data', '50000', '90000', '89000', '789000', '450000',
       '670000', '76000', '0.7', '0.9', '0.45', '1.0', '87.5', '78.5',
       '89.7'], dtype='<U32')

In [18]:
emp

array([['TCS', 'Capgemini', 'Reliance', 'IBM', 'Microsoft', 'Seimens',
        'NTT Data'],
       ['50000', '90000', '89000', '789000', '450000', '670000', '76000'],
       ['0.7', '0.9', '0.45', '1.0', '87.5', '78.5', '89.7']],
      dtype='<U32')

In [24]:
for data in emp.flatten(order='F'):                           #Fortran order styling means column wise representation of data
    print(data)

TCS
50000
0.7
Capgemini
90000
0.9
Reliance
89000
0.45
IBM
789000
1.0
Microsoft
450000
87.5
Seimens
670000
78.5
NTT Data
76000
89.7


In [29]:
for data in emp.flatten():                           #C style ordering means row wise representation of data which is default
    print(data)

TCS
Capgemini
Reliance
IBM
Microsoft
Seimens
NTT Data
50000
90000
89000
789000
450000
670000
76000
0.7
0.9
0.45
1.0
87.5
78.5
89.7


In [64]:
num=np.arange(16).reshape(4,4)
num

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
for i in num:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


In [66]:
for i in np.nditer(num):                      #used to print the array element wise
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [79]:
for i in np.nditer(num,order='F',flags=['external_loop']):         #used to print the array column wise
    print(i)

[  0  16  64 144]
[  1  25  81 169]
[  4  36 100 196]
[  9  49 121 225]


In [68]:
for array in np.nditer(num,op_flags=['readwrite']):
    array[...]=array*array
    

In [69]:
num

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])